name: First Workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print msg1
        run: echo "Hello Dude"
      - name: Print msg2
        run: echo "Good Bye dude"
        
